### ISSUE TITLE
Define C library to port from

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/serial.cr#1]
Find possible candidates for a base library.

**Comment by Sija** [comment]
## Libserialport

http://sigrok.org/wiki/Libserialport

### Pros:
- C
- Wide cross-platform support — _Linux_, _Mac OS X_, _FreeBSD_, _Windows_ & _Android_
- Good 'nuff lookin' thread safety model
- Few bugs, as per _Bugzilla_ — http://sigrok.org/bugzilla/buglist.cgi?bug_status=__open__&product=libserialport

### Cons:
- LGPL license - could be MIT or sth, but IMO it's still ok
- Lack of examples, howtos et al. Found one — https://github.com/martinling/libserialport/issues/11#issuecomment-135889019

**Comment by Sija** [comment]
## Serial Communication Library

https://github.com/wjwwood/serial

### Pros:
- MIT license

### Cons:
- C++
- Low development activity
- Moar bugs than _Libserialport_, as per — https://github.com/wjwwood/serial/issues
- Python-based build system

**Comment by marceloboeira** [comment]
@Sija I think Libserialport is the best option, giving its cross operating system support mostly.

**Comment by Sija** [comment]
@marceloboeira That's my bet too. So I guess we have a winner :)

**Comment by Sija** [comment]
There's also [Termios](https://github.com/crystal-lang/crystal/blob/master/src/lib_c/x86_64-linux-gnu/c/termios.cr) which I've missed before.
